apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeacon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeacon-testing
  template:
    metadata:
      labels:
        app: kubeacon-testing
    spec:
      serviceAccountName: kubeacon-testing-sa
      containers:
      - name: kubeacon
        image: guillh/kubeacon-testing:latest
        imagePullPolicy: Always
